project:
  type: website

website:
  title: "site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - models/featureEngineering.ipynb
      - models/Random_forest.ipynb
      - models/Decision_Tree_automl.ipynb
      - models/LogisticRegression.ipynb
      - models/KNN_and_XGB.ipynb
      - models/svm-model.ipynb
      - about.qmd

format:
  html:
    theme: Journal
    css: styles.css
    toc: true
    # mainfont: serif
